const fs = require('fs');
let s = "import * as React from 'react';\n";
s += "import { Link } from 'react-router-dom';\n";
s += "import { ArrowLeft, Database, Server, Lock, Activity, GitCommit } from 'lucide-react';\n";
s += "import { FadeIn } from '../components/ui/FadeIn';\n";
s += "import { Badge } from '../components/ui/Badge';\n";
s += "import { Card } from '../components/ui/Card';\n\n";
s += "export function ProjectRAG() {\n";
s += "  React.useEffect(() => { window.scrollTo(0, 0); }, []);\n\n";
s += "  return (\n";
s += "    <div className=\"mx-auto w-full max-w-4xl px-6 py-24\">\n";
s += "      <Link to=\"/\" className=\"inline-flex items-center gap-2 text-zinc-400 hover:text-zinc-50 transition-colors mb-12\">\n";
s += "        <ArrowLeft size={16} /> Back to Portfolio\n";
s += "      </Link>\n";
s += "      \n";
s += "      <FadeIn>\n";
s += "        <h1 className=\"text-4xl md:text-5xl font-extrabold tracking-tight text-zinc-50 mb-6\">Enterprise-Grade Java RAG System</h1>\n";
s += "        <p className=\"text-xl text-zinc-400 mb-8 leading-relaxed\">\n";
s += "          A production-ready Retrieval-Augmented Generation application integrating a locally hosted LLM with Spring Boot and Qdrant.\n";
s += "        </p>\n";
s += "        <div className=\"flex flex-wrap gap-2 mb-16\">\n";
s += "          <Badge>Java</Badge><Badge>Spring Boot</Badge><Badge>LangChain4j</Badge><Badge>Qdrant</Badge><Badge>PostgreSQL</Badge><Badge>Docker</Badge>\n";
s += "        </div>\n";
s += "      </FadeIn>\n\n";
s += "      <div className=\"space-y-20\">\n";
s += "        <FadeIn delay={0.1}>\n";
s += "          <h2 className=\"text-2xl font-bold text-zinc-100 mb-6 border-b border-zinc-800 pb-2\">Problem Statement</h2>\n";
s += "          <p className=\"text-zinc-400 leading-relaxed text-lg\">\n";
s += "            Standard Large Language Models lack context of proprietary internal documentation, leading to hallucinations or generic answers. Enterprise environments require secure, high-accuracy query systems that do not expose internal documents to third-party cloud APIs (like OpenAI). The goal was to build a system that keeps data on-premise while delivering highly accurate, context-aware AI interactions.\n";
s += "          </p>\n";
s += "        </FadeIn>\n\n";
s += "        <FadeIn delay={0.2}>\n";
s += "          <h2 className=\"text-2xl font-bold text-zinc-100 mb-6 border-b border-zinc-800 pb-2\">System Architecture & API Flow</h2>\n";
s += "          <p className=\"text-zinc-400 leading-relaxed mb-6\">The architecture follows a strict service-oriented design, segregating the document ingestion pipeline from the user query pipeline.</p>\n";
s += "          \n";
s += "          <div className=\"grid md:grid-cols-2 gap-6 mb-6\">\n";
s += "            <Card className=\"p-6 border-zinc-800 bg-zinc-900/30\">\n";
s += "              <div className=\"flex items-center gap-3 mb-4\"><Database className=\"text-zinc-300\" size={20}/><h3 className=\"font-bold text-zinc-100\">1. Ingestion Flow</h3></div>\n";
s += "              <ul className=\"space-y-3 text-sm text-zinc-400\">\n";
s += "                <li>• Documents uploaded via REST API.</li>\n";
s += "                <li>• Parsed and chunked (overlapping semantic chunks).</li>\n";
s += "                <li>• Embeddings generated locally and stored in <strong>Qdrant</strong>.</li>\n";
s += "                <li>• Document metadata mapped and stored in <strong>PostgreSQL</strong>.</li>\n";
s += "              </ul>\n";
s += "            </Card>\n";
s += "            <Card className=\"p-6 border-zinc-800 bg-zinc-900/30\">\n";
s += "              <div className=\"flex items-center gap-3 mb-4\"><Server className=\"text-zinc-300\" size={20}/><h3 className=\"font-bold text-zinc-100\">2. Query Flow</h3></div>\n";
s += "              <ul className=\"space-y-3 text-sm text-zinc-400\">\n";
s += "                <li>• User query embedded via the same local model.</li>\n";
s += "                <li>• Similarity search executed against Qdrant.</li>\n";
s += "                <li>• Context hydrated with PostgreSQL metadata.</li>\n";
s += "                <li>• Final prompt passed to local LLM via <strong>LangChain4j</strong>.</li>\n";
s += "              </ul>\n";
s += "            </Card>\n";
s += "          </div>\n";
s += "        </FadeIn>\n\n";
s += "        <FadeIn delay={0.3}>\n";
s += "          <h2 className=\"text-2xl font-bold text-zinc-100 mb-6 border-b border-zinc-800 pb-2\">Database Design & Data Integrity</h2>\n";
s += "          <p className=\"text-zinc-400 leading-relaxed mb-4\">\n";
s += "            A dual-database strategy was employed to optimize both semantic search and transactional integrity.\n";
s += "          </p>\n";
s += "          <div className=\"bg-zinc-950 border border-zinc-800 rounded-lg p-6 font-mono text-sm text-zinc-300 overflow-x-auto whitespace-pre\">\n";
s += "            // PostgreSQL Schema (Metadata & User States)\n";
s += "            Table: documents\n";
s += "            - id (UUID, PK)\n";
s += "            - filename (VARCHAR)\n";
s += "            - upload_date (TIMESTAMP)\n";
s += "            - access_level (ENUM)\n\n";
s += "            // Qdrant Vector Schema (Embeddings)\n";
s += "            Collection: "enterprise_knowledge"\n";
s += "            - vector: [768 dimensions]\n";
s += "            - payload: { doc_id: UUID, chunk_index: INT, content: TEXT }\n";
s += "          </div>\n";
s += "        </FadeIn>\n\n";
s += "        <FadeIn delay={0.4}>\n";
s += "          <h2 className=\"text-2xl font-bold text-zinc-100 mb-6 border-b border-zinc-800 pb-2\">Authentication & Security Flow</h2>\n";
s += "          <p className=\"text-zinc-400 leading-relaxed mb-4\">\n";
s += "            To secure the REST APIs, a robust JWT-based authentication system was implemented.\n";
s += "          </p>\n";
s += "          <ul className=\"list-disc list-outside ml-5 space-y-4 text-zinc-400 leading-relaxed marker:text-zinc-600\">\n";
s += "            <li><strong className=\"text-zinc-200\">Stateless Auth:</strong> Spring Security filter chain intercepts requests, validating JWT signatures without requiring session state.</li>\n";
s += "            <li><strong className=\"text-zinc-200\">Role-Based Access Control:</strong> Endpoints are secured via method-level security, ensuring only authorized personnel can upload documents to the vector DB.</li>\n";
s += "            <li><strong className=\"text-zinc-200\">Data Isolation:</strong> Queries are filtered by the user's access level before performing the vector search.</li>\n";
s += "          </ul>\n";
s += "        </FadeIn>\n\n";
s += "        <FadeIn delay={0.5}>\n";
s += "          <h2 className=\"text-2xl font-bold text-zinc-100 mb-6 border-b border-zinc-800 pb-2\">Engineering Trade-offs & Scalability</h2>\n";
s += "          <div className=\"space-y-6\">\n";
s += "            <div>\n";
s += "              <h3 className=\"text-lg font-bold text-zinc-200 mb-2 flex items-center gap-2\"><Lock size={18}/> Cloud vs. Local LLM</h3>\n";
s += "              <p className=\"text-zinc-400 text-sm leading-relaxed\"><strong className=\"text-zinc-300\">Trade-off:</strong> Using a local LLM ensures 100% data privacy and zero API costs, but requires higher upfront server hardware (GPU/RAM) and increases inference latency compared to OpenAI APIs. Chosen local to meet strict enterprise privacy constraints.</p>\n";
s += "            </div>\n";
s += "            <div>\n";
s += "              <h3 className=\"text-lg font-bold text-zinc-200 mb-2 flex items-center gap-2\"><GitCommit size={18}/> Chunking Strategy</h3>\n";
s += "              <p className=\"text-zinc-400 text-sm leading-relaxed\"><strong className=\"text-zinc-300\">Trade-off:</strong> Smaller document chunks yield highly precise vector matches but lose broad context. Larger chunks keep context but risk polluting the LLM prompt window. Optimized via an overlapping sliding-window approach.</p>\n";
s += "            </div>\n";
s += "            <div>\n";
s += "              <h3 className=\"text-lg font-bold text-zinc-200 mb-2 flex items-center gap-2\"><Activity size={18}/> Scalability Considerations</h3>\n";
s += "              <p className=\"text-zinc-400 text-sm leading-relaxed\">The entire stack is containerized with Docker. The Spring Boot backend is completely stateless, meaning it can scale horizontally behind a load balancer, while Qdrant handles vector sharding inherently.</p>\n";
s += "            </div>\n";
s += "          </div>\n";
s += "        </FadeIn>\n";
s += "      </div>\n";
s += "    </div>\n";
s += "  );\n";
s += "}\n";
fs.writeFileSync('src/pages/ProjectRAG.tsx', s);

